name: Release
on:
  release:
    types:
      - published

concurrency:
  group: ci-release
  cancel-in-progress: true

jobs:
  promote_release:
    uses: ./.github/workflows/promote-release.yml
    with:
      type: latest
      ref: ${{ github.event.release.tag_name }}
    secrets:
      DX_BEARER_TOKEN: ${{ secrets.DX_BEARER_TOKEN }}

  link-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
      - name: Create Linear release
        uses: linear/linear-release-action@af56a9a388625921f3757a2f988e4d7aca958377 # v0.15.0
        with:
          access_key: ${{ secrets.LINEAR_ACCESS_KEY }}
          name: ${{ github.event.repository.name }} (${{ github.event.release.tag_name }})
          version: ${{ github.event.release.tag_name }}
          links: ${{ github.event.release.html_url }}
